language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script: mvn clean package
after_success:
- mvn clean cobertura:cobertura coveralls:report
notifications:
  slack:
    on_failure: always
    on_success: always
    secure: OCA5Nhg5ntGigUle8fHzix2CPFehwAC+pDCreNZvbtaTlrQkFj1E7abnT5F9fblSij/eTqECSyoQIek7y/4NMu5VSiN1Ck3UZ5LMoeRm0tkUvrhiXyvV6ddZ/kUqd28aIPs391Uc6yy939Fyc1OackTgtHzaIUII/HNoWAugGu/0y36NIvYQhnS2YwIfIASIYxHw/HOJBs99r9qplIQ4UEPLHYt3Os7HOkUKJC1NhCEIRpAv7CjIT42/fR+FbiCrgPlyHuXcXcLlm+e6mSIkackYk6j6GWP6mcncRWRftn0TLvpyY8NMvvo+EQfczt/XUrQNyAPtWjJ68R2AjIblrMkXbnzaMG7riw1ITeK9rInoz+6O8yfpqKPNzdM/CYP7XEGSdyMjSJgIYleQvKax/Z2Qc7DxfZtSCJrzWjLfABqH9pHjHAuINr0NyDA3W9SaOz4Rv8SwlLUi+F8ekhgaVkhpBBu0eUC1e+TPOS8vcSyo0e4FjK7+Wi20IiYf5jdx23KHH/2FEDZ10z2ewmOvl03cxu/PDHONHLya/2uRvuI3+5cbYac3lvtm3sEt4ZnIckz7jgR2vNSJZem6CQOI6q2MESUzrxKBTZi1buBXJtt/h81Td1Kv/Y7oYarffhjzrUKYD4YZ/uSMytGFCLBle8p1OlvGDSel+8Kk8tDnFts=
