language: java
jdk:
- oraclejdk8
script: mvn clean package
after_success:
- mvn clean cobertura:cobertura coveralls:report
notifications:
  slack:
    secure: EyAXuaQAAQP/1WOo5x3ip1PD0X0aLVWwhmlrzSPvZHvDIyW/hAffjvnnsWSiSFfZJsiAUTzJ5rsNdyQA56qU36Egm8UoqGRc47ySwmS+MVSKcIGDt4JqdaAz8XSpMulSWnGMI6BuNSCHkKNOj2qHUGh9+t+JXldW/aXy4Qr2GUMYjBsjk1I4YPSuw/yHW5MdvmFy5W9M7RnFWphsr9TgZDmo6aGW7OoKdIMyo9zoJegOX7RnMl5RBkcTg5ZOSKummA9TxwbIp/yOYMWVj1iPgdO+ursIqsW4sTfYrOaTdac+NrH2zW5jRQxx9R5Bhx9k5s1xnCbLXAW6fM6vfq1yU/skJm+v7/3i3/6gb9H6nCIL0K0YcfyV3ExcDUGtJsOyfAMu+wGAoE4T5STiG0OvOCpWEZuVJQqhQDWw4LHPRC+Q9Wvvb8ZrSfxuo8hV7F/svfFIMflTDtCinpsFRLa8EPd11b5gN3a3wv//nuQ37Z3sWJOrvwzZ8/TLOIT24m2wiP9xzfzF0NxnzjhPa+koUNSf4TJxy+u+JE5KtrLsLn4TM1LOlSUABXD7FAiYOlCRWSs9amoyqvutHwgW99MYcaonqnEeUndhI/yDZza8B+lWvhRRbmOjh04Rw3kICZI0i0DENRApIpWDOuNht5C9n1ail2CjAsmfjSsS7YXPfKY=
